### ISSUE TITLE
'Configuration' object has no attribute 'disable_log'

### ISSUE THREAD

**Issue by rsingh5** [BIDS-Apps/CPAC#29]
I have a simple configuration [Pipeline_config.txt](https://github.com/BIDS-Apps/CPAC/files/1679153/Pipeline_config.txt) to run CPAC and I am getting  'Configuration' object has no attribute 'disable_log' error. I have tried different configuration options but not able to find how to fix it. Can you please help?

Here is the log
180130-20:12:37,959 workflow INFO:
	 VERSION: CPAC 1.0.2

Setting maximum number of cores per participant to 1
Setting number of participants at once to 1
Setting OMP_NUM_THREADS to 1
Setting MKL_NUM_THREADS to 1
Setting ANTS/ITK thread usage to 1

Maximum potential number of cores that might be used during this run: 1

++ 3dcalc: AFNI version=AFNI_16.3.08 (Nov  4 2016) [64-bit]
++ Authored by: A cast of thousands
Process Process-7:
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/bin/miniconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/bin/miniconda/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py", line 291, in prep_workflow
    if c.disable_log and c.disable_log == True:
AttributeError: 'Configuration' object has no attribute 'disable_log'

**Comment by rsingh5** [comment]
I even tried bids/cpac:v1.0.2_disable_log_2 Docker app but I am getting same issue. Any idea what can be wrong?

**Comment by sgiavasis** [comment]
Hello @rsingh5,

I think this is related to a change in the pipeline config parameter names. The option to disable logging was introduced in CPAC v1.0.2, but the template pipeline config might not have the "disable_log" key introduced.

This changed in CPAC v1.0.3- can you try this fork and branch and see if it resolves your problem?
https://github.com/sgiavasis/CPAC/tree/v1.0.3_merged

Best,
Steve
