### ISSUE TITLE
Can't save Data Config file with Singularity GUI

### ISSUE THREAD

**Issue by egarza** [BIDS-Apps/CPAC#34]
This is a different issue than the other I posted.

Now I can easily run CPAC GUI using singularity without problems. However, when I try to save the BIDS formatted dataset I have, it gives me the following error:

```
Saving data settings file:
/media/egarza/INP_MRI_Backup/projects/INP/addimex_tms/data/mri/test/data_settings_test4.yaml


Generating data configuration file..
Checking participants.tsv file for site information:
/media/egarza/INP_MRI_Backup/projects/INP/addimex_tms/data/mri/bids_sofia/participants.tsv
No site information found in the participants.tsv file.
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 349, in <lambda>
    self.Bind(wx.EVT_BUTTON, lambda event: self.save(event,'run'), id=ID_RUN_EXT)
  File "/usr/local/miniconda/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 604, in save
    if self.run(path) > 0:
  File "/usr/local/miniconda/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 388, in run
    CPAC.utils.build_data_config.run(config)
  File "/usr/local/miniconda/lib/python2.7/site-packages/CPAC/utils/build_data_config.py", line 1534, in run
    config_dir=settings_dct["outputSubjectListLocation"])
  File "/usr/local/miniconda/lib/python2.7/site-packages/CPAC/utils/build_data_config.py", line 871, in get_BIDS_data_dct
    sites_dct=sites_subs_dct)
  File "/usr/local/miniconda/lib/python2.7/site-packages/CPAC/utils/build_data_config.py", line 1377, in get_nonBIDS_data
    raise Exception(err)
Exception: 

[!] No anatomical input file paths found given the data settings provided.

Anatomical file template being used: /media/egarza/INP_MRI_Backup/projects/INP/addimex_tms/data/mri/bids_sofia/*/sub-*/ses-*/anat/sub-*_ses-*_T1w.nii.gz


(run.py:13131): Gtk-WARNING **: Unable to find default local file monitor type

```
We do have a participants.tsv. It seems the anatomical path is looking for a folder before '/sub-*/' which should not exists. 

Thanks

Ed

**Comment by egarza** [comment]
Hi, I still have this problem and I think it is because CPAC is looking for a `ses` folder before the subject, but I only have one session. So, any idea how it can skip the session?

Thanks
